---
title: Blog
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Prashant Sharma
bio: Passionate coder | CS Post-Graduate
description: A blog about technology and stuff related
external-image: false
picture: assets/images/PrashantSharma.jpg
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume
url: http://sharmapacific.in
permalink: "/:title/"
disqus:
  shortname: 
  categories:
  - 
  - 
linkedin: sharmapacific
twitter: sharmapacific1
github: sharmapacific
medium: sharmapacific
email: sharma.pacific1@gmail.com
authors:
  PrashantSharma:
    name: Prashant Sharma
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/PrashantSharma.jpg
    twitter: sharmapacific1
width: normal
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
- blog
show-author: true
animation: true
plugins:
- jekyll-seo-tag
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-admin
- jekyll-sitemap
jekyll-mentions:
  base_url: https://github.com
compress_html:
  ignore:
    envs:
    - development
    - stage
exclude:
- travis.sh
- Rakefile
- README.md
- Gemfile
- Gemfile.lock
- FAQ.md
